spring:
  config:
    name: school
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 8353

  error:
    whitelabel:
      enabled: false
    path: /error
    include-message: always
    include-binding-errors: always

#  servlet:
#  session:
#  timeout: 15m